### ISSUE TITLE
High fail rate at connecting to the swarm with 0.0.11

### ISSUE THREAD

**Issue by beingalink** [mafintosh/dat-next-next#1]
While in rare cases I can get the dat-next-next instances to connect, mostly the receiving dat-next-next instance gets stuck at "connecting to the swarm". This working/non-working behavior is under the exact same conditions (same up-to-date dat-next-next versions on both sides and on the same different platforms at both ends (works -> abort -> doesn't work -> abort -> still doesn't work -> etc.)). A debug-logfile can be downloaded [here](https://www.dropbox.com/s/ui91dyhbrz44ynw/dat-next-next.log?dl=0).

My test case is the ca. 1GB big ubuntu iso-image file: `dat-next-next ubuntu-14.04.4-desktop-amd64.iso`.

**Comment by mafintosh** [comment]
@beingalink is this still relevant?

**Comment by beingalink** [comment]
Nope, not at all. Sorry, forgot to close. Thanks for all your work on this technology!
